### ISSUE TITLE
Update the database schema to handle new columns and line types added to the MET-11.0.0-beta3 output. 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#119]
## Describe the Enhancement ##
MET development version 11.0.0-beta3 made several changes to the "stat" output. This issue is the update the database schema accordingly to handle this new data for MET version 11.0.0.

- Issue dtcenter/MET#1942 enhances Point-Stat to write new SEEPS and SEEPS_MPR line types. Both of these new line type should be added to the schema. Note that dtcenter/MET#1942 will enhance Grid-Stat to also compute the SEEPS line type, but should make no additional changes to the schema.

- Issue dtcenter/MET#2206 adds a new CRPS_EMP_FAIR column to the end of the ECNT line type.

Sample data for this issue can be found in the nightly build output in seneca:/d1/projects/MET/MET_regression/develop/NB20220922/MET-develop/test_output (or a more recent date). But here's a tarfile of output with the subset of ECNT and SEEPS outputs:
[sample_ecnt_seeps.tar.gz](https://github.com/dtcenter/METdataio/files/9628333/sample_ecnt_seeps.tar.gz)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
By the end of the beta4 development cycle.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @venitahagerty 
- [x] Select **scientist(s)** or **no scientist** required: none required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will create corresponding issues for aggregating/plotting this data.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues

Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
Two new SEEPS line types were added to the schema and the code, and a new field was added to ECNT.
