### ISSUE TITLE
Create a MET data reformatter 

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METdatadb#121]
## Describe the New Feature ##
Provide a data reformatter that can reformat MET ASCII output from stat_analysis, point_stat, MODE, MTD, etc. to be consistent with the output created by METviewer (when the same MET data has been loaded into the METviewer database).  This will allow the other METplus analysis tools to handle a consistent format of input data.

### Acceptance Testing ###
**Sample point stat, mode, and MTD data:**

From Will Mayfield:
[dump.out.txt](https://github.com/dtcenter/METdataio/files/9787957/dump.out.txt)

From MET tutorial:
[mode_120000L_20050807_120000V_120000A_obj.txt](https://github.com/dtcenter/METdataio/files/9787911/mode_120000L_20050807_120000V_120000A_obj.txt)

[mtd_20050807_030000V_2d.txt](https://github.com/dtcenter/METdataio/files/9787914/mtd_20050807_030000V_2d.txt)

**And get data to resemble this format (with header in all lower case as well):**
[line.data.txt](https://github.com/dtcenter/METdataio/files/9787931/line.data.txt)

_This is what METviewer would produce as data after loading the MET data into the database_

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792542

### Assignee ###
- [x] Select **engineer(s)** Hank Fisher and Minna Win
- [x Select **scientist(s)** Will Mayfield

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Support for reformatting the .stat file from MET point stat for the following line types:
FHO
CNT
CTC
CTS
SL1L2

Utilizing the METdataio METdbLoad reader (and xml reader) which requires specifying a specification xml file.  In addition, a YAML configuration file is required which specifies the location of the specification xml file, the output directory, and the output filename.
