### ISSUE TITLE
Add more automation to test_tables.py

### ISSUE THREAD

**Issue by venitahagerty** [dtcenter/METdatadb#31]
## Automatically compare floating point numbers and row counts ##
The current data testing program for METdbLoad, test_tables.py, needs to be more automated. It compares two MySQL subdatabases, usually one created by MVLoad, and one by METdbLoad. It finds rows that are different, but pairs of floating point numbers (such as 0.47938 and 0.47938000000000003) are not equal, and need to be checked manually.

Also, comparing of row counts by table would be faster if done automatically. Row counts are given for the current queries, but the queries have row limits. Counts of table rows need to be generated for both subdatabases, and compared.

### Time Estimate ###
*2 days.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Automate floating point checks.*
- [x] *Automate table row count comparisons.*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*NONE.*

### Assignee ###
- [ ] Venita Hagerty
- [ ] **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
