### ISSUE TITLE
Enhance METdataio schema to handle new/modified MPR and ORANK columns introduced for MET 12.0.0 beta6

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#320]
## Describe the Enhancement ##
Issue dtcenter/MET#2924 and corresponding pull requests dtcenter/MET#2939 and dtcenter/MET#2942 made changes to the MPR and ORANK line types. The METdataio schema needs to be updated to handle the diffs described below:
1. In MPR, `CLIMO_MEAN` is renamed `OBS_CLIMO_MEAN`.
2. In MPR, `CLIMO_STDEV` is renamed `OBS_CLIMO_STDEV`.
3. In MPR, `CLIMO_CDF` is renamed `OBS_CLIMO_CDF`.
4. In MPR, new `FCST_CLIMO_MEAN` and `FCST_CLIMO_STDEV` are added to the end of the line.
5. In ORANK, `CLIMO_MEAN` is renamed `OBS_CLIMO_MEAN`.
6. In ORANK `CLIMO_STDEV` is renamed `OBS_CLIMO_STDEV`.
7. In ORANK, new `FCST_CLIMO_MEAN` and `FCST_CLIMO_STDEV` are added to the end of the line.

Please see updated [MPR line type](https://met.readthedocs.io/en/develop/Users_Guide/point-stat.html#id24) and [ORANK line type](https://met.readthedocs.io/en/develop/Users_Guide/ensemble-stat.html#id7) tables.

@bikegeek, it is not clear to me if changes are needed in METplotpy, METcalcpy, and METviewer. I'm not sure if/how data from these columns are used in those components. Please let me know if you'd like me to write up additional issues for them.

METreformat code for the MPR linetype is impacted due to the addition of new columns:
https://github.com/dtcenter/METdataio/issues/321

### Time Estimate ###
1 day?

### Sub-Issues ###
- [x] Retrieve ORANK and MPR sample data from the MET nightly regression tests
- [x] Make necessary changes to the METdbLoad/ush/constants.py module
- [x] Make necessary changes to the   METdbLoad/sql/mv_mysql.sql file 
- [x] Create and provide content for the update_for_6_0_beta6.sql file
- [ ] Create a directory METdbLoad/tests/update_schema_6.0_beta6 and create a test to verify that the updated and new columns exist

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues

Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Created issue https://github.com/dtcenter/METdataio/issues/321 for the METreformat module to address additional columns added to the MPR linetype

**Comment by JohnHalleyGotway** [comment]
@bikegeek FYI, the dtcenter/MET#2924 issue was completed today and the final PR merged. You can find updated MPR and ORANK data tomorrow in the output from the MET nightly build run on seneca.
