### ISSUE TITLE
Add loading of updated MCTC and MCTS line types for new HSS statistic.

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METdatadb#54]
## Describe the Enhancement ##

Heidke Skill Score is being updated to accommodate CPC needs. The MCTS line type in MET version 10.1.0 will include two new columns, HSS_EC and EC_VALUE. The EC_VALUE column will also be added to the MCTC line type to avoid making the EC_VALUE a new required configuration option for plotting.

MET issue to generate new statistics: dtcenter/MET#1749
METviewer issue to plot HSS_EC: dtcenter/METviewer#285

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Venita
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
Here is the stat file with MCTC and MCTS data. Please remoce .csv - I had to add it for GitHub
[grid_stat_GTG_latlon_060000L_20130827_180000V.stat.csv](https://github.com/dtcenter/METdatadb/files/6704834/grid_stat_GTG_latlon_060000L_20130827_180000V.stat.csv)

**Comment by TatianaBurek** [comment]
More data on kiowa
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta1/feature_1749/MET-feature_1749_hss/test_output/grid_stat

**Comment by venitahagerty** [comment]
Tatiana let me know that there are 4 new fields in MCTS:

HSS_EC  
HSS_EC_BCL 
HSS_EC_BCU 
EC_VALUE

**Comment by venitahagerty** [comment]
Made the changes in constants.py and write_stat_sql.py to add the 4 columns to line_data_mcts, and the 1 column to line_data_mctc. Needs the updated mv_mysql.sql from METviewer. Successfully tested with data provided. Pushed to the develop branch.
