### ISSUE TITLE
Load new DMAP columns for G and GBETA.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#62]
## Describe the Enhancement ##
The issue dtcenter/met#1673 and corresponding pull request dtcenter/met#1857 add new columns to the distance map (DMAP) line type created by the Grid-Stat tool.

This adds 3 new columns to the end of the existing DMAP line type: G, GBETA, and BETA_VALUE. All 3 columns are floating point numbers. Note that G will always have a value in the output, but GBETA and BETA_VALUE will only have a value when VX_MASK = FULL. When VX_MASK != FULL, GBETA = BETA_VALUE = NA.

Please see corresponding METviewer issue for plotting these stats:
dtcenter/METviewer#323

Please see existing documentation for more details about the [configuration options](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html?highlight=gbeta#distance-map), [science](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html#beta-and-g-beta), and [equations](https://met.readthedocs.io/en/develop/Users_Guide/appendixC.html?highlight=gbeta#g-and-g-beta).

Sample data can be found in kiowa:/d1/projects/MET/MET_regression/develop/NB20210818/MET-develop/test_output/met_test_scripts/grid_stat/grid_stat_120000L_20050807_120000V_dmap.txt.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Prior to the coordinated METplus 4.1.0 release.

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Venita
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
Here is the sample data (remove.txt)
[grid_stat_120000L_20050807_120000V.stat.txt](https://github.com/dtcenter/METdatadb/files/7009875/grid_stat_120000L_20050807_120000V.stat.txt)

**Comment by TatianaBurek** [comment]
Updated schema file:
https://github.com/dtcenter/METviewer/blob/issue/324-dmap_stats/sql/mv_mysql.sql

**Comment by venitahagerty** [comment]
Added new fields g, g_beta, and beta_value to line_data_dmap in constants.py. Requires version of mv_mysql.sql with new columns in line_data_dmap (in METviewer repo). Ran with test data file provided by Tatiana.
