### ISSUE TITLE
Enhance METdatadb to load the new SSIDX STAT line type from Stat-Analysis.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#63]
## Describe the Enhancement ##
The pull request dtcenter/MET#1892 for issue dtcenter/MET#1788 adds a new STAT line type that is created by Stat-Analysis. The SSIDX line type is documented in the Stat-Analysis MET User's Guide chapter on the [feature branch](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#id10). After that PR is approved/merged, please see the [develop branch](https://met.readthedocs.io/en/develop/Users_Guide/stat-analysis.html#id10) instead.

Please ask @JohnHalleyGotway any questions about how to handle the data.

A sample data file is provided here:
[ssidx_sample.tar.gz](https://github.com/dtcenter/METdatadb/files/7100392/ssidx_sample.tar.gz)

One file with FCST_VAR = OBS_VAR = GO_INDEX.
One file with FCST_VAR = OBS_VAR = SS_INDEX.
Another option is CBS_INDEX but no example is provided here.
Note that strings in the header columns can get long. For example, MODEL = fcst model name, reference model name. By default, when multiple strings are encountered in the input, their unique values are written to the output as a comma-separated list.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
To be included in the coordinated METplus version 4.1.0 release.

### Funding Source ###
Funded via the DTC AF project (2712221). See @michelleharrold.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Venita
- [x] Select **scientist(s)** or **no scientist** required: no scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Source issue in MET: dtcenter/MET#1788
- [x] Related issue in METviewer to plot this data: dtcenter/METviewer#327
 
## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold and/or @hertneky can provide additional SSIDX test data after running it for the AF LIS project.

**Comment by hertneky** [comment]
@JohnHalleyGotway @venitahagerty @TatianaBurek I have some sample CBS Index data on Kiowa:/d1/projects/AF/lis/metprd/stat_analysis

These were run by initialization, month (Dec, Jan, Feb), season (only winter)

**Comment by TatianaBurek** [comment]
Here are the files:
[cbs_index_winter.stat.txt](https://github.com/dtcenter/METdatadb/files/7138584/cbs_index_winter.stat.txt)
[cbs_index_january.stat.txt](https://github.com/dtcenter/METdatadb/files/7138585/cbs_index_january.stat.txt)

I also added a new line type to the schema:
https://github.com/dtcenter/METviewer/blob/issue/327-SSIDX/sql/mv_mysql.sql

Venita, please keep in mind that we are discussing to increase the size  limit of the model column in stat_header table from 40 to 60 or 80 because of this line type. I will let you know.

**Comment by TatianaBurek** [comment]
The size of the 'model' column is increased to 80 chars
