### ISSUE TITLE
Read in stratospheric data and put it into the format required for the means calculation

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METdatadb#66]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
Make reading in netCDF data more general to support non-MET version netCDF.  A netCDF file is on kiowa:/d1/personal/kalb/stratosphere/SSWC_v1.0_varFull_ERAi_d20130106_s20121107_e20130307_c20160701.nc

The python notebook which reads these files and computes zonal means is attached here:
[pyzome_zonal-mean-example-data.pdf](https://github.com/dtcenter/METdatadb/files/7515911/pyzome_zonal-mean-example-data.pdf)
[pyzome_zonal-mean-example-data.ipynb.txt](https://github.com/dtcenter/METdatadb/files/7515913/pyzome_zonal-mean-example-data.ipynb.txt)

### Time Estimate ###
??

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] Read the SSW files into a python xarray

### Relevant Deadlines ###
Ideally the zonal mean data would be added by mid December, and this is the first step of the processing.  So, sometime in the next few weeks would be great 

### Funding Source ###
2793541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Fortunately the code worked almost as is with one minor tweak to the import
