### ISSUE TITLE
Setup GitHub actions to implement regression testing of loading METdatadb.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#67]
## Describe the New Feature ##

This issue was discussed during the METplus Analysis Tools project meeting on 1/5/22. No automated testing of METdatadb's load functionality currently exists. This issue is to establish that automated testing for METdatadb via GitHub actions by porting over similar logic from dtcenter/METplus. This issue is assigned to @venitahagerty, as she is the lead developer on METdatadb. However, this task also requires input from the following staff:
- @georgemccabe to advise on the GHA automated testing workflow in METplus.
- @TatianaBurek to provide the input data (i.e. existing MET output data) and advise on loading logic.
- @JohnHalleyGotway to gain more experience with GHA, ensure consistent testing workflow logic across components, and grant whatever additional permissions are needed.

The tasks for this issue include, but are not limited, to:
- [x] Schedule a kick-off working meeting for Tuesday 1/11/22 1:00-2:00pm MST (@JohnHalleyGotway).
- [x] Identify the location of existing MET output data that should be used for this testing logic (@TatianaBurek).
On dakota:
```
> du -sch /d3/projects/METViewer/test_data/load_data/load/met_data/
1.4G	/d3/projects/METViewer/test_data/load_data/load/met_data/
```

- [x] @jprestop copy this data over to mohawk along with other test datasets as the met_test user.

And make it accessible via:
   https://dtcenter.ucar.edu/dfiles/code/METplus/METdatadb
We'll need a tar.gz file of this data as well so it's easily pulled.

- [ ] Decide where test infrastructure files should live. Recommend METdatdb/.github/docker.

- [ ] @venitahagerty create a new Dockerfile in there which inherits from the mysql (or mariadb?) image and checks out the version of METdatadb to be tested. Adapt this existing Dockerfile:
https://github.com/dtcenter/METdatadb/blob/main_v1.0/METdbLoad/docker/Dockerfile

Ideally, parameterize this Dockerfile to support both mysql and mariadb.

Please see existing METplus use case that calls METdatadb load:
https://github.com/dtcenter/METplus/blob/develop/parm/use_cases/met_tool_wrapper/METdbLoad/METdbLoad.conf

- [ ] Consider storing that dataset as a data volume in a new METdatadb-dev repository in DockerHub.
- [ ] Define simple GitHub actions to trigger on commits to feature branches. 
- [ ] Define more robust GitHub actions to trigger on the submission of pull requests.
- [ ] Define logic/tools to diff the contents of 2 databases (@venitahagerty does this already exist?).

The general logic for the last item is:
- Pull an existing Docker image from DockerHub containing a reference database pre-loaded.
- Pull the input test Docker data volume from DockerHub.
- Checkout the test version of METdatadb and load data from that Docker data volume.
- Run diffing logic to flag any unexpected differences.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
If NCAR folks work on this - split: 2702691 & 2792541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
See readme in:
https://github.com/dtcenter/METdatadb/tree/main_v1.0/METdbLoad/tests
for description of existing test software to compare 2 subdatabases. This has been run manually up to now.

**Comment by jprestop** [comment]
@JohnHalleyGotway @TatianaBurek 
I have copied the data from dakota:/d3/projects/METViewer/test_data/load_data/load/met_data/ to mohawk:/d2/www/dtcenter/dfiles/code/METplus/METviewer/test_data/load_data/load/met_data. The tar_file of this data, however, is at the top level of the METviewer directory on mohawk:/d2/www/dtcenter/dfiles/code/METplus/METviewer and is named load_met_data.20220112.tar.gz.  

Please let me know if you want me to change anything regarding the location and/or name of the file.

Please note that I have included the date in the file name. Until mohawk becomes the official location for updates to this dataset, any updates to the data will need to be made both on dakota and on mohawk, and a new tar file would need to be created.  As discussed earlier, once you are set up on seneca for testing and development, mohawk will be the official location for this data and will be linked to from other machines.

**Comment by jprestop** [comment]
Per email conversation, we changed the structure of the directories on mohawk and the tar file name.  This data now exists at /d2/www/dtcenter/dfiles/code/METplus/METdatadb/METdatadb_Data/develop/met_test and the tar file is located at and named: /d2/www/dtcenter/dfiles/code/METplus/METdatadb/METdatadb_Data/develop/load_met_data-develop.tgz.  We intended to have specific versions, like develop (and v1.1, etc.) at /d2/www/dtcenter/dfiles/code/METplus/METdatadb/METdatadb_Data/.

**Comment by venitahagerty** [comment]
Approved and merged.
