### ISSUE TITLE
Load new TC-Diagnostics output from TC-Pairs.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METdatadb#87]
## Describe the New Feature ##
dtcenter/MET#2168 defines a new MET tool named TC-Diag. And dtcenter/MET#392 enhances TC-Pairs to read the Tropical Cyclone Diagnostics output from TC-Diag (or other sources) and incorporate it into the output of the TC-Pairs tool.

Exactly HOW that output should be incorporated has not yet been clearly defined. Two options being considered are:
1. Tack on additional columns to the end of the existing TCMPR line type.
2. Create a new TCDIAG output line type that corresponds to the existing TCMPR line type but contains storm diagnostics data instead of ADECK/BDECK differences.

The big caveat is that number, type, and order of the diagnostics data could change run to run based on the user configuration. So the challenge is loading that data intelligently into the database.

We are looking to METplus Analysis Tools team for direction on how this data should be formatted.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @venitahagerty and @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: @jvigh 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] dtcenter/MET#2168
- [ ] dtcenter/MET#392

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
This issue was resolved by issues 131 and 141. This issue was closed by completion of PR 139.
